config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'plays#index'
  resources :plays do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :plays
end

app/models/play.rb
class Play < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :reviews
    has_one_attached :main_image
    validates :title,presence: true, length: {minimum: 5,maximum: 40}
    validates :desc,presence: true, length: {minimum: 50}
    validates :director,presence: true
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :play
    belongs_to :user
    validates :comment, presence: true, length: {minimum:50}
    validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :plays
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
    before_action :find_plays, only: [:show,:edit,:update,:destroy]
    before_action :authenticate_user!, only: [:new, :edit]
    def index
        if params[:category].blank?
            @plays=Play.all.order("created_at DESC")
        else
            @category_id=Category.find_by(name: params[:category]).id
            @plays=Play.where(:category_id => @category_id).order("created_at DESC")
        end
    end
    def new
        @play=current_user.plays.build
        @categories=Category.all.map{ |c| [c.name, c.id]}
    end
    def create
        @play=current_user.plays.build(play_params)
        puts "#{play_params[:category_id]} debug"
        @play.category_id=play_params[:category_id]
        if @play.save
            flash[:notice]="Play cretaed successfully"
            redirect_to play_path(@play)
        else
            render :new, status: :unprocessable_entity
        end
    end
    def show
        @play=Play.find(params[:id])
    end
    def edit
        @categories=Category.all.map{ |c| [c.name, c.id]}
    end
    def update
        @play.category_id=params[:category_id]
        if @play.update(play_params)
            flash[:notice]="Play Updated Successfully"
            redirect_to play_path(@play)
        else
            render 'edit',status: :unprocessable_entity
        end
    end
    def destroy
        @play.destroy
        flash[:alert]= "Deleted Play!"
        redirect_to plays_path
    end

    private
    def play_params
        params.require(:play).permit(:title,:desc,:director,:main_image,:category_id)
    end
    def find_plays
        @play=Play.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_play
    before_action :find_review, only: [:edit,:update,:destroy]
    before_action :authenticate_user!, only: [:new,:edit]
    def new
        @review=Review.new()
    end
    def create
        @review=Review.create(review_params)
        @review.play_id=@play.id
        @review.user_id=current_user.id
        puts "#{@review.user_id} #{@review.play_id}"
        if @review.save
            redirect_to play_path(@play)
        else
            @play.errors.full_messages.each do |err|
                puts "#{err} error"
            end
            render :new, status: :unprocessable_entity
        end
    end

    def edit 
    end
    def update
        if @review.update(review_params)
            redirect_to play_path(@play)
        else
            render :edit, status: :unprocessable_entity
        end
    end
    def destroy
        @review.destroy
        redirect_to play_path(@play)
    end
    private 
    def review_params
        params.require(:review).permit(:rating, :comment)
    end
    def find_play
        @play=Play.find(params[:play_id])
    end
    def find_review
        @review=Review.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def star_rating(rating, max_rating = 5)
        full_stars = rating.floor
        half_star = rating % 1 > 0 ? 1 : 0
        empty_stars = max_rating - full_stars - half_star
    
        stars_html = ''
        full_stars.times { stars_html += tag.i '', class: 'fas fa-star' }
        half_star.times { stars_html += tag.i '', class: 'fas fa-star-half-alt' }
        empty_stars.times { stars_html += tag.i '', class: 'far fa-star' }
    
        stars_html.html_safe
      end
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Broadway</title>
    <meta name="turbolinks-cache-control" content="no-cache">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
  <nav class="navbar navbar-expand-lg " >
  <div class="container-fluid">
    <%= link_to 'BroadwayApp' , root_path, class: "navbar-brand fs-2 mx-5"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <% if user_signed_in? %>
      <ul class="navbar-nav">
        <li class="nav-item pt-2">
          <%= link_to 'Add Play',new_play_path,class:"nav-link active fs-4"%>
        </li>
      </ul>
      <% end %>
      <ul class="navbar-nav">
        <li class="nav-item dropdown pt-2" id="changeUrlButton">
          <a class="nav-link dropdown-toggle fs-4" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
            <li><%= link_to category.name,plays_path(category: category.name),class: "dropdown-item fs-4" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Logout',destroy_user_session_path,  data: { turbo_method: 'delete',turbo_confirm: 'Are sure for logout? '},class:"nav-link active fs-4 mx-5"%>
        </li>
        <% else %>
         <li class="nav-item">
          <%= link_to 'Signup',new_user_registration_path,class:"nav-link active fs-4 mx-5"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Login',new_user_session_path,class:"nav-link active fs-4 mx-5"%>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
    <div class="container">
    
    <%= yield %>
    </div>
    <footer class="mt-4">
      <span>
      <a href="#">Broadway</a> | &nbsp;<span class="far fa-copyright">&nbsp;&nbsp;</span>2024 All Rights Reserved.</span>
    </footer>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script>
    $('document').ready(function(){ 
      $('.alert').fadeOut(5000);
      $('.btn-close').click(function(){
        $('.alert').slideUp();
      })
     })
  </script>
</html>

app/views/plays/_form.html.erb
<%= simple_form_for(@play) do |f| %>
<% if @play.persisted? %>
    <h2 class="text-center">Update Play Record</h2>
<% else %>
    <h2 class="text-center">Create Play Records</h2>
<% end %>
<div class="mb-3">
    <%= f.label :"Title :",class:"form-label"%>
    <%= f.text_field :title,class:"form-control",required:true,placeholder:"Enter Title Here....."%>
    <% if @play.errors.any? %>
    <% @play.errors.full_messages_for(:title).each do |err|%>
        <p style="font-size:1rem;color:red"><%= err %></p>
        <% break %>
    <% end %>
    <% end %>
</div>
<div class="mb-3">
    <%= f.label :"Description :",class:"form-label" %>
    <%= f.text_area :desc,class:"form-control",required:true,placeholder:"Enter Description of your play...."%>
    <% if @play.errors.any? %>
    <% @play.errors.full_messages_for(:desc).each do |err|%>
        <p style="font-size:1rem;color:red"><%= err %></p>
        <% break %>
    <% end %>
    <% end %>
</div>
<div class="mb-3">
    <%= f.label :"Director Name:",class:"form-label"%>
    <%= f.text_field :director,class:"form-control",class:"form-control",required:true,placeholder:"Enter Director Name...."%>
    <% if @play.errors.any? %>
    <% @play.errors.full_messages_for(:director).each do |err|%>
        <p style="font-size:1rem;color:red"><%= err %></p>
        <% break %>
    <% end %>
    <% end %>
</div>
<% if @play.persisted? %>
    <div class="mb-3">
    <%= f.label :"Play Category:",class:"form-label"%> <br>
    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Play Category",class: "form-select form-select-lg",required:true%>
    <% if @play.errors.any? %>
    <% @play.errors.full_messages_for(:category).each do |err|%>
        <p style="font-size:1rem;color:red"><%= err %></p>
        <% break %>
    <% end %>
    <% end %>
</div>
<% else %>
    <div class="mb-3">
    <%= f.label :"Play Category:",class:"form-label"%> <br>
    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Play Category",class: "form-select form-select-lg",required:true%>
    <% if @play.errors.any? %>
    <% @play.errors.full_messages_for(:category).each do |err|%>
        <p style="font-size:1rem;color:red"><%= err %></p>
        <% break %>
    <% end %>
    <% end %>
</div>
<% end %>
<div class="row mb-3">
<%= f.label :"Play Image"%>
<%= f.file_field :main_image%>
</div>
<div class="d-grid gap-2 col-6 mx-auto">
<% if @play.persisted? %>
    <%= f.submit "Update Play",class:"btn btn-primary"%>
<% else %>
    <%= f.submit "Add Play",class:"btn btn-primary"%>
<% end %>
<%= link_to 'Back',plays_path,class:"btn btn-warning"%>
</div>
<% end %>

app/views/plays/edit.html.erb
<%= render 'form' %>

app/views/plays/index.html.erb
<% if params[:category].present? %>
    <h1 class='text-center mt-2 mb-2'><%= params[:category] %></h1>
<% else %>
    <h2 class="text-center mt-2 mb-2">All Play's</h2>
<% end %>
<% if @plays.count == 0 %>
    <h3>There are no  plays added yet.</h3>
<% else %>
    <div class="row">
    <% @plays.each do |play| %>
    <div class="col-md-3 mx-auto">
        <%= link_to(image_tag(play.main_image, class: "play"),play_path(play)) %>
    </div>
    <% end %>
    </div>
<% end %>

app/views/plays/new.html.erb
<%= render 'form' %>

app/views/plays/show.html.erb
<div class="row mt-5">
    <div class="col-md-4">
        <% if @play.main_image.present? %>
            <%= image_tag @play.main_image,class:"play-show" %>
        <% end %>
    </div>
    <div class="col-md-8 px-5">
        <div class="play-info">
            <h2 class="play-title"><%= @play.title %></h2> 
            <h4 class="play-direcor"><span>By </span> <%= @play.director %></h4>
            <h4 class="play-director"><%= @play.category.name %></h4>
            <p class="play-desc"><%= @play.desc %></p>
            <% if user_signed_in? %>
                <% if @play.user_id == current_user.id %>
                    <%= link_to 'Edit',edit_play_path(@play),class:"btn btn-outline-warning text-white btn-lg mx-5"%>
                    <%= link_to 'Delete',@play, data: {turbo_method: 'delete', turbo_confirm: "are you sure"},class:"btn btn-outline-danger btn-lg"%>
                <% end %>
                <% if current_user.id != @play.user_id%>
                <%= link_to "Add Reviews",new_play_review_path(@play),class:"btn btn-outline-info"%>
                <% end %>
                <% end %>
        </div>
    </div>
</div>

<div class="row">
    <div class="md-12 px-5">
        <div class="reviews">
            <%= render @play.reviews %>
        </div>
    </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([@play, @play.reviews.build]) do |f| %>
<div class=" row mb-3">
    <%= f.label :"Rating :",class:"col-sm-2 col-form-label"%>
    <div class="col-sm-10">
        <%= f.number_field :rating,class:"form-control",required:true%>
        <% if f.object.errors.any? %>
            <% f.object.errors.full_messages_for(:rating).each do |err| %>
                <p style="color:red;font-size:1rem"><%= err %></p>
            <% end %>
        <% end %>
    </div>
</div>
<div class="row mb-3">
    <%= f.label :"Comment :",class:"col-sm-2 col-form-label"%>
    <div class="col-sm-10">
    <%= f.text_field :comment,class:"form-control",required:true%>
    </div>
</div>
<%= f.submit "Add comment",class:"btn btn-info m-auto"%>
<% end %>

app/views/reviews/_review.html.erb
<div class="review-container mt-3">
  <h1 class="review-title">Review</h1>
  <div class="review-card">
    <div class="review-header">
      <div class="review-user-info">
        <!-- User's name -->
        <p class="review-user-name"><%= User.find(review.user_id).email %> </p>
        <!-- Date of the review -->
        <p class="review-date"><%= review.created_at.strftime('%B %d, %Y') %></p>
      </div>
    </div>
    <div class="review-body">
        <% if review.rating >=4 %>
            <h3 class="review-heading">Good Experience!</h3>
        <% elsif review.rating >= 2 %>
            <h3 class="review-heading">Good Experience!</h3>
        <% else %>
            <h3 class="review-heading">Bad Experience</h3>
        <% end %>
      <!-- Static 4-star rating -->
      <div class="review-rating">
        <div class="stars">
          <%= star_rating(review.rating) %>
        </div>
      </div>
    </div>
    <div class="review-content">
        <div class="review-user-info">
        <!-- User's name -->
        <p class="review-user-name"><%= review.comment %></p>
        <!-- Date of the review -->
        <% if user_signed_in? %>
        <% if current_user.id == review.user_id %>
            <p class="review-date">
            <%= link_to 'Edit ',edit_play_review_path(review.play,review), class:"btn btn-outline-info"%>
            <%= link_to 'Delete',[review.play,review], data: {turbo_method: 'delete',turbo_confirm: "Are you sure?"},class:"btn btn-outline-danger"%></p>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/edit.html.erb
<%= simple_form_for([@play, @review]) do |f| %>
<h2 class="text-center">Edit Review</h2>
<div class=" row mb-3">
    <%= f.label :"Rating :",class:"col-sm-2 col-form-label"%>
    <div class="col-sm-10">
        <%= f.number_field :rating,class:"form-control"%>
    </div>
</div>
<div class="row mb-3">
    <%= f.label :"Comment :",class:"col-sm-2 col-form-label"%>
    <div class="col-sm-10">
    <%= f.text_field :comment,class:"form-control"%>
    </div>
</div>
<%= f.submit "Add comment",class:"btn btn-info m-auto"%>
<% end %>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1">
    <div class="new-review-form">
        <h1 class="text-center">Post Review</h1>
        <%= render 'form' %>
    </div>
</div>